# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50345adda8c5f5994023a167a8dfb7df9add0b137a7430f1fe550942d017402f4b3d67b58597aca277d3979932cf47541c898d26c0025cc7d68e84b48df6f964

test:
  secret_key_base: d77980e9793fcde199e683df68267b4409b86e2a760f623da80d3b8fd330ebd7826e47acbe6f0e26941729e201b0f06b04edd7f32d0ade86c9ea861239214897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
