# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 162c0efd1a44a1021d1c3bb8c243ab2dfdffecebdba50b2608062a17591d466875f59a8f19e9b397130877970f444aab317e261ffdee0341a05cdc57db362486

test:
  secret_key_base: 43a67001f70cc17026e439e84a3781f53e438ff743583102c06290536eb0ed48110c88312c1c4c67bca31e23588509f4624b9e4cc3b0fe67485a1c22235b4462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
