# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 378dd444fa532dc2eb83904d80611a935923cc0f843c3fc4cad760bab8cc1bebc04c5babe21d442ea0913025c034cdb69087e25b3b53e28da8f32dc5a3eed606

test:
  secret_key_base: e1186d088b5871993fdb51d83674c3be9ee4b35b628a9927809b93c6430d0a5d403ca35c75460563fe38f1f76995e8f9dd6ef673daa357c801e66acb00157e91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
