# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e848ba0dbae9fb3736c3e806a3de215d3e8e3f8525a01d299cd5b577517d4647f5222ba69ab05ec439ecea532aca418dbf6d816e7723069de11d88788fb74bd

test:
  secret_key_base: c0c8a970409d4de4361a3bfffc388cc59d90c1c5e946a3a153b99d3ad4acb3a8ab75508dc01b2e6e8d3aacd1952f88c4498a018176c008c7b0d78f861f8198ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
